version: '2'
services:
  pgloader:
    container_name: migration.pgloader
    image: dimitri/pgloader:latest
    volumes:
      - .:/home/root
  postgres:
    container_name: migration.pgsql
    build:
      context: ./docker/postgres
      dockerfile: Dockerfile
    environment:
      - POSTGRES_PASSWORD=secret
    ports:
     - "54666:5432"
    volumes:
     - pgsqldata:/var/lib/postgresql/data
    networks:
     - migratenet
  mysql:
    container_name: migration.mysql
    image: mysql:5.6
    volumes:
      - mysqldata:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=foodkitdb"
      - "MYSQL_USER=foodkituser"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"
    ports:
        - "33666:3306"
    networks:
     - migratenet
networks:
  migratenet:
    driver: "bridge"
volumes:
  pgsqldata:
    driver: "local"
  mysqldata:
    driver: "local"
